// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: music_service.proto
#ifndef GRPC_music_5fservice_2eproto__INCLUDED
#define GRPC_music_5fservice_2eproto__INCLUDED

#include "music_service.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace music {

class MapReduceService final {
 public:
  static constexpr char const* service_full_name() {
    return "music.MapReduceService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status AggregateStream(::grpc::ClientContext* context, const ::music::StreamList& request, ::music::PlayCounts* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::music::PlayCounts>> AsyncAggregateStream(::grpc::ClientContext* context, const ::music::StreamList& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::music::PlayCounts>>(AsyncAggregateStreamRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::music::PlayCounts>> PrepareAsyncAggregateStream(::grpc::ClientContext* context, const ::music::StreamList& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::music::PlayCounts>>(PrepareAsyncAggregateStreamRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void AggregateStream(::grpc::ClientContext* context, const ::music::StreamList* request, ::music::PlayCounts* response, std::function<void(::grpc::Status)>) = 0;
      virtual void AggregateStream(::grpc::ClientContext* context, const ::music::StreamList* request, ::music::PlayCounts* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::music::PlayCounts>* AsyncAggregateStreamRaw(::grpc::ClientContext* context, const ::music::StreamList& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::music::PlayCounts>* PrepareAsyncAggregateStreamRaw(::grpc::ClientContext* context, const ::music::StreamList& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status AggregateStream(::grpc::ClientContext* context, const ::music::StreamList& request, ::music::PlayCounts* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::music::PlayCounts>> AsyncAggregateStream(::grpc::ClientContext* context, const ::music::StreamList& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::music::PlayCounts>>(AsyncAggregateStreamRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::music::PlayCounts>> PrepareAsyncAggregateStream(::grpc::ClientContext* context, const ::music::StreamList& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::music::PlayCounts>>(PrepareAsyncAggregateStreamRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void AggregateStream(::grpc::ClientContext* context, const ::music::StreamList* request, ::music::PlayCounts* response, std::function<void(::grpc::Status)>) override;
      void AggregateStream(::grpc::ClientContext* context, const ::music::StreamList* request, ::music::PlayCounts* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::music::PlayCounts>* AsyncAggregateStreamRaw(::grpc::ClientContext* context, const ::music::StreamList& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::music::PlayCounts>* PrepareAsyncAggregateStreamRaw(::grpc::ClientContext* context, const ::music::StreamList& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_AggregateStream_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status AggregateStream(::grpc::ServerContext* context, const ::music::StreamList* request, ::music::PlayCounts* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_AggregateStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_AggregateStream() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_AggregateStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AggregateStream(::grpc::ServerContext* /*context*/, const ::music::StreamList* /*request*/, ::music::PlayCounts* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAggregateStream(::grpc::ServerContext* context, ::music::StreamList* request, ::grpc::ServerAsyncResponseWriter< ::music::PlayCounts>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_AggregateStream<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_AggregateStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_AggregateStream() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::music::StreamList, ::music::PlayCounts>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::music::StreamList* request, ::music::PlayCounts* response) { return this->AggregateStream(context, request, response); }));}
    void SetMessageAllocatorFor_AggregateStream(
        ::grpc::MessageAllocator< ::music::StreamList, ::music::PlayCounts>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::music::StreamList, ::music::PlayCounts>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_AggregateStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AggregateStream(::grpc::ServerContext* /*context*/, const ::music::StreamList* /*request*/, ::music::PlayCounts* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AggregateStream(
      ::grpc::CallbackServerContext* /*context*/, const ::music::StreamList* /*request*/, ::music::PlayCounts* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_AggregateStream<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_AggregateStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_AggregateStream() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_AggregateStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AggregateStream(::grpc::ServerContext* /*context*/, const ::music::StreamList* /*request*/, ::music::PlayCounts* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_AggregateStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_AggregateStream() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_AggregateStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AggregateStream(::grpc::ServerContext* /*context*/, const ::music::StreamList* /*request*/, ::music::PlayCounts* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAggregateStream(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_AggregateStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_AggregateStream() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->AggregateStream(context, request, response); }));
    }
    ~WithRawCallbackMethod_AggregateStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AggregateStream(::grpc::ServerContext* /*context*/, const ::music::StreamList* /*request*/, ::music::PlayCounts* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AggregateStream(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_AggregateStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_AggregateStream() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::music::StreamList, ::music::PlayCounts>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::music::StreamList, ::music::PlayCounts>* streamer) {
                       return this->StreamedAggregateStream(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_AggregateStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status AggregateStream(::grpc::ServerContext* /*context*/, const ::music::StreamList* /*request*/, ::music::PlayCounts* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedAggregateStream(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::music::StreamList,::music::PlayCounts>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_AggregateStream<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_AggregateStream<Service > StreamedService;
};

class UserBehaviorService final {
 public:
  static constexpr char const* service_full_name() {
    return "music.UserBehaviorService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status AnalyzeUsers(::grpc::ClientContext* context, const ::music::StreamList& request, ::music::UserStatsList* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::music::UserStatsList>> AsyncAnalyzeUsers(::grpc::ClientContext* context, const ::music::StreamList& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::music::UserStatsList>>(AsyncAnalyzeUsersRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::music::UserStatsList>> PrepareAsyncAnalyzeUsers(::grpc::ClientContext* context, const ::music::StreamList& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::music::UserStatsList>>(PrepareAsyncAnalyzeUsersRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void AnalyzeUsers(::grpc::ClientContext* context, const ::music::StreamList* request, ::music::UserStatsList* response, std::function<void(::grpc::Status)>) = 0;
      virtual void AnalyzeUsers(::grpc::ClientContext* context, const ::music::StreamList* request, ::music::UserStatsList* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::music::UserStatsList>* AsyncAnalyzeUsersRaw(::grpc::ClientContext* context, const ::music::StreamList& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::music::UserStatsList>* PrepareAsyncAnalyzeUsersRaw(::grpc::ClientContext* context, const ::music::StreamList& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status AnalyzeUsers(::grpc::ClientContext* context, const ::music::StreamList& request, ::music::UserStatsList* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::music::UserStatsList>> AsyncAnalyzeUsers(::grpc::ClientContext* context, const ::music::StreamList& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::music::UserStatsList>>(AsyncAnalyzeUsersRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::music::UserStatsList>> PrepareAsyncAnalyzeUsers(::grpc::ClientContext* context, const ::music::StreamList& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::music::UserStatsList>>(PrepareAsyncAnalyzeUsersRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void AnalyzeUsers(::grpc::ClientContext* context, const ::music::StreamList* request, ::music::UserStatsList* response, std::function<void(::grpc::Status)>) override;
      void AnalyzeUsers(::grpc::ClientContext* context, const ::music::StreamList* request, ::music::UserStatsList* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::music::UserStatsList>* AsyncAnalyzeUsersRaw(::grpc::ClientContext* context, const ::music::StreamList& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::music::UserStatsList>* PrepareAsyncAnalyzeUsersRaw(::grpc::ClientContext* context, const ::music::StreamList& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_AnalyzeUsers_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status AnalyzeUsers(::grpc::ServerContext* context, const ::music::StreamList* request, ::music::UserStatsList* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_AnalyzeUsers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_AnalyzeUsers() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_AnalyzeUsers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AnalyzeUsers(::grpc::ServerContext* /*context*/, const ::music::StreamList* /*request*/, ::music::UserStatsList* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAnalyzeUsers(::grpc::ServerContext* context, ::music::StreamList* request, ::grpc::ServerAsyncResponseWriter< ::music::UserStatsList>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_AnalyzeUsers<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_AnalyzeUsers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_AnalyzeUsers() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::music::StreamList, ::music::UserStatsList>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::music::StreamList* request, ::music::UserStatsList* response) { return this->AnalyzeUsers(context, request, response); }));}
    void SetMessageAllocatorFor_AnalyzeUsers(
        ::grpc::MessageAllocator< ::music::StreamList, ::music::UserStatsList>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::music::StreamList, ::music::UserStatsList>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_AnalyzeUsers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AnalyzeUsers(::grpc::ServerContext* /*context*/, const ::music::StreamList* /*request*/, ::music::UserStatsList* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AnalyzeUsers(
      ::grpc::CallbackServerContext* /*context*/, const ::music::StreamList* /*request*/, ::music::UserStatsList* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_AnalyzeUsers<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_AnalyzeUsers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_AnalyzeUsers() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_AnalyzeUsers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AnalyzeUsers(::grpc::ServerContext* /*context*/, const ::music::StreamList* /*request*/, ::music::UserStatsList* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_AnalyzeUsers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_AnalyzeUsers() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_AnalyzeUsers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AnalyzeUsers(::grpc::ServerContext* /*context*/, const ::music::StreamList* /*request*/, ::music::UserStatsList* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAnalyzeUsers(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_AnalyzeUsers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_AnalyzeUsers() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->AnalyzeUsers(context, request, response); }));
    }
    ~WithRawCallbackMethod_AnalyzeUsers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AnalyzeUsers(::grpc::ServerContext* /*context*/, const ::music::StreamList* /*request*/, ::music::UserStatsList* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AnalyzeUsers(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_AnalyzeUsers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_AnalyzeUsers() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::music::StreamList, ::music::UserStatsList>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::music::StreamList, ::music::UserStatsList>* streamer) {
                       return this->StreamedAnalyzeUsers(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_AnalyzeUsers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status AnalyzeUsers(::grpc::ServerContext* /*context*/, const ::music::StreamList* /*request*/, ::music::UserStatsList* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedAnalyzeUsers(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::music::StreamList,::music::UserStatsList>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_AnalyzeUsers<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_AnalyzeUsers<Service > StreamedService;
};

class GenreAnalysisService final {
 public:
  static constexpr char const* service_full_name() {
    return "music.GenreAnalysisService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status AnalyzeGenres(::grpc::ClientContext* context, const ::music::StreamList& request, ::music::GenreAnalysisResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::music::GenreAnalysisResponse>> AsyncAnalyzeGenres(::grpc::ClientContext* context, const ::music::StreamList& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::music::GenreAnalysisResponse>>(AsyncAnalyzeGenresRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::music::GenreAnalysisResponse>> PrepareAsyncAnalyzeGenres(::grpc::ClientContext* context, const ::music::StreamList& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::music::GenreAnalysisResponse>>(PrepareAsyncAnalyzeGenresRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void AnalyzeGenres(::grpc::ClientContext* context, const ::music::StreamList* request, ::music::GenreAnalysisResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void AnalyzeGenres(::grpc::ClientContext* context, const ::music::StreamList* request, ::music::GenreAnalysisResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::music::GenreAnalysisResponse>* AsyncAnalyzeGenresRaw(::grpc::ClientContext* context, const ::music::StreamList& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::music::GenreAnalysisResponse>* PrepareAsyncAnalyzeGenresRaw(::grpc::ClientContext* context, const ::music::StreamList& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status AnalyzeGenres(::grpc::ClientContext* context, const ::music::StreamList& request, ::music::GenreAnalysisResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::music::GenreAnalysisResponse>> AsyncAnalyzeGenres(::grpc::ClientContext* context, const ::music::StreamList& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::music::GenreAnalysisResponse>>(AsyncAnalyzeGenresRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::music::GenreAnalysisResponse>> PrepareAsyncAnalyzeGenres(::grpc::ClientContext* context, const ::music::StreamList& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::music::GenreAnalysisResponse>>(PrepareAsyncAnalyzeGenresRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void AnalyzeGenres(::grpc::ClientContext* context, const ::music::StreamList* request, ::music::GenreAnalysisResponse* response, std::function<void(::grpc::Status)>) override;
      void AnalyzeGenres(::grpc::ClientContext* context, const ::music::StreamList* request, ::music::GenreAnalysisResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::music::GenreAnalysisResponse>* AsyncAnalyzeGenresRaw(::grpc::ClientContext* context, const ::music::StreamList& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::music::GenreAnalysisResponse>* PrepareAsyncAnalyzeGenresRaw(::grpc::ClientContext* context, const ::music::StreamList& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_AnalyzeGenres_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status AnalyzeGenres(::grpc::ServerContext* context, const ::music::StreamList* request, ::music::GenreAnalysisResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_AnalyzeGenres : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_AnalyzeGenres() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_AnalyzeGenres() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AnalyzeGenres(::grpc::ServerContext* /*context*/, const ::music::StreamList* /*request*/, ::music::GenreAnalysisResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAnalyzeGenres(::grpc::ServerContext* context, ::music::StreamList* request, ::grpc::ServerAsyncResponseWriter< ::music::GenreAnalysisResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_AnalyzeGenres<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_AnalyzeGenres : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_AnalyzeGenres() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::music::StreamList, ::music::GenreAnalysisResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::music::StreamList* request, ::music::GenreAnalysisResponse* response) { return this->AnalyzeGenres(context, request, response); }));}
    void SetMessageAllocatorFor_AnalyzeGenres(
        ::grpc::MessageAllocator< ::music::StreamList, ::music::GenreAnalysisResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::music::StreamList, ::music::GenreAnalysisResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_AnalyzeGenres() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AnalyzeGenres(::grpc::ServerContext* /*context*/, const ::music::StreamList* /*request*/, ::music::GenreAnalysisResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AnalyzeGenres(
      ::grpc::CallbackServerContext* /*context*/, const ::music::StreamList* /*request*/, ::music::GenreAnalysisResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_AnalyzeGenres<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_AnalyzeGenres : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_AnalyzeGenres() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_AnalyzeGenres() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AnalyzeGenres(::grpc::ServerContext* /*context*/, const ::music::StreamList* /*request*/, ::music::GenreAnalysisResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_AnalyzeGenres : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_AnalyzeGenres() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_AnalyzeGenres() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AnalyzeGenres(::grpc::ServerContext* /*context*/, const ::music::StreamList* /*request*/, ::music::GenreAnalysisResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAnalyzeGenres(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_AnalyzeGenres : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_AnalyzeGenres() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->AnalyzeGenres(context, request, response); }));
    }
    ~WithRawCallbackMethod_AnalyzeGenres() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AnalyzeGenres(::grpc::ServerContext* /*context*/, const ::music::StreamList* /*request*/, ::music::GenreAnalysisResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AnalyzeGenres(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_AnalyzeGenres : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_AnalyzeGenres() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::music::StreamList, ::music::GenreAnalysisResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::music::StreamList, ::music::GenreAnalysisResponse>* streamer) {
                       return this->StreamedAnalyzeGenres(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_AnalyzeGenres() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status AnalyzeGenres(::grpc::ServerContext* /*context*/, const ::music::StreamList* /*request*/, ::music::GenreAnalysisResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedAnalyzeGenres(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::music::StreamList,::music::GenreAnalysisResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_AnalyzeGenres<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_AnalyzeGenres<Service > StreamedService;
};

class RecommendationService final {
 public:
  static constexpr char const* service_full_name() {
    return "music.RecommendationService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Recommend(::grpc::ClientContext* context, const ::music::RecommendationRequest& request, ::music::RecommendationResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::music::RecommendationResponse>> AsyncRecommend(::grpc::ClientContext* context, const ::music::RecommendationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::music::RecommendationResponse>>(AsyncRecommendRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::music::RecommendationResponse>> PrepareAsyncRecommend(::grpc::ClientContext* context, const ::music::RecommendationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::music::RecommendationResponse>>(PrepareAsyncRecommendRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void Recommend(::grpc::ClientContext* context, const ::music::RecommendationRequest* request, ::music::RecommendationResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Recommend(::grpc::ClientContext* context, const ::music::RecommendationRequest* request, ::music::RecommendationResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::music::RecommendationResponse>* AsyncRecommendRaw(::grpc::ClientContext* context, const ::music::RecommendationRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::music::RecommendationResponse>* PrepareAsyncRecommendRaw(::grpc::ClientContext* context, const ::music::RecommendationRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Recommend(::grpc::ClientContext* context, const ::music::RecommendationRequest& request, ::music::RecommendationResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::music::RecommendationResponse>> AsyncRecommend(::grpc::ClientContext* context, const ::music::RecommendationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::music::RecommendationResponse>>(AsyncRecommendRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::music::RecommendationResponse>> PrepareAsyncRecommend(::grpc::ClientContext* context, const ::music::RecommendationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::music::RecommendationResponse>>(PrepareAsyncRecommendRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Recommend(::grpc::ClientContext* context, const ::music::RecommendationRequest* request, ::music::RecommendationResponse* response, std::function<void(::grpc::Status)>) override;
      void Recommend(::grpc::ClientContext* context, const ::music::RecommendationRequest* request, ::music::RecommendationResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::music::RecommendationResponse>* AsyncRecommendRaw(::grpc::ClientContext* context, const ::music::RecommendationRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::music::RecommendationResponse>* PrepareAsyncRecommendRaw(::grpc::ClientContext* context, const ::music::RecommendationRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Recommend_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Recommend(::grpc::ServerContext* context, const ::music::RecommendationRequest* request, ::music::RecommendationResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Recommend : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Recommend() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Recommend() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Recommend(::grpc::ServerContext* /*context*/, const ::music::RecommendationRequest* /*request*/, ::music::RecommendationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRecommend(::grpc::ServerContext* context, ::music::RecommendationRequest* request, ::grpc::ServerAsyncResponseWriter< ::music::RecommendationResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Recommend<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Recommend : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Recommend() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::music::RecommendationRequest, ::music::RecommendationResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::music::RecommendationRequest* request, ::music::RecommendationResponse* response) { return this->Recommend(context, request, response); }));}
    void SetMessageAllocatorFor_Recommend(
        ::grpc::MessageAllocator< ::music::RecommendationRequest, ::music::RecommendationResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::music::RecommendationRequest, ::music::RecommendationResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Recommend() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Recommend(::grpc::ServerContext* /*context*/, const ::music::RecommendationRequest* /*request*/, ::music::RecommendationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Recommend(
      ::grpc::CallbackServerContext* /*context*/, const ::music::RecommendationRequest* /*request*/, ::music::RecommendationResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Recommend<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Recommend : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Recommend() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Recommend() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Recommend(::grpc::ServerContext* /*context*/, const ::music::RecommendationRequest* /*request*/, ::music::RecommendationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Recommend : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Recommend() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Recommend() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Recommend(::grpc::ServerContext* /*context*/, const ::music::RecommendationRequest* /*request*/, ::music::RecommendationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRecommend(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Recommend : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Recommend() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Recommend(context, request, response); }));
    }
    ~WithRawCallbackMethod_Recommend() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Recommend(::grpc::ServerContext* /*context*/, const ::music::RecommendationRequest* /*request*/, ::music::RecommendationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Recommend(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Recommend : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Recommend() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::music::RecommendationRequest, ::music::RecommendationResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::music::RecommendationRequest, ::music::RecommendationResponse>* streamer) {
                       return this->StreamedRecommend(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Recommend() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Recommend(::grpc::ServerContext* /*context*/, const ::music::RecommendationRequest* /*request*/, ::music::RecommendationResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRecommend(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::music::RecommendationRequest,::music::RecommendationResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Recommend<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Recommend<Service > StreamedService;
};

}  // namespace music


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_music_5fservice_2eproto__INCLUDED
